{{- if .Values.development }}
apiVersion: v1
kind: Secret
metadata:
  name: lodestar-backend-configuration
type: Opaque
stringData:
  AUTH_SERVER_URL: "{{ .Values.authServerUrl }}"
  AUTH_CLIENT_ID: {{ .Values.authClientId }}"
  LODESTAR_GITLAB_API_URL: "{{ .Values.lodestarGitlabApiUrl }}"
  JWT_PUBKICKEY_LOCATION: "{{ .Values.jwtPublicKeyLocation }}"
  JWT_ISSUER: "{{ .Values.jwtIssuer }}"
  DATABASE_SERVICE_NAME: "{{ .Values.mongodbServiceName }}"
  MONGODB_USER: "{{ .Values.mongodbUser }}"
  MONGODB_PASSWORD: "{{ .Values.mongodbPassword }}"
  MONGODB_DATABASE: "{{ .Values.mongodbDatabase }}"
  MONGODB_ADMIN_PASSWORD: "{{ .Values.mongodbAdminPassword }}"
{{- end }}
