name: Build Container

on:
  push:
    branches:
      - oidc

jobs:
  build:
    if: github.repository == 'mcanoy/lodestar-backend'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13.0.1
    - name: SonarCloud Static Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn verify sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }} -q
    - name: Find and Replace Commit
      uses: jacobtomlinson/gha-find-replace@0.1.1
      with:
        find: "###GIT_COMMIT###"
        replace: "${{ github.sha }}"
        include: ".s2i"
    - name: Find and Replace Reader
      uses: jacobtomlinson/gha-find-replace@0.1.1
      with:
        find: "quarkus.http.auth.policy.role-reader.roles-allowed=.*"
        replace: "${{ secrets.READERS }}"
        include: "src/main/resources/application.properties"
    - name: Find and Replace Writer
      uses: jacobtomlinson/gha-find-replace@0.1.1
      with:
        find: "quarkus.http.auth.policy.role-writer.roles-allowed.*"
        replace: "${{ secrets.WRITERS }}"
        include: "src/main/resources/application.properties"
    - uses: redhat-cop/github-actions/s2i@v2
      with:
        base: registry.access.redhat.com/ubi8/openjdk-11:1.3
        output_image: "quay.io/mcanoy/lodestar-backend:${{ github.sha }}"
        image_push_registry: quay.io
        image_push_username: ${{ secrets.QUAY_USERNAME }}
        image_push_password: ${{ secrets.QUAY_PASSWORD }}
        image_tags: master
